name = "MyCoolPackage"
uuid = "9c920d37-3fee-41b4-b611-4e3d1ef863fd"
authors = ["Joshua Moore"]
version = "1.0.0-DEV"

[deps]
Example = "7876af07-990d-54b4-ab0e-23690620f79a"

[compat]
julia = "1.10.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
